#!/bin/bash

DB_USER="daniel"
DB_PASSWORD="801599"
DB_NAME="documents_db"
DB_HOST="localhost"
DB_PORT="5432"

docker exec -t db_postgres pg_dump -U "DB_USER" -d "DB_NAME" | gzip > db_backups/backup.sql.gz