"""::))

Revision ID: 0bb747eb022a
Revises: 
Create Date: 2025-08-07 19:11:23.869195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb747eb022a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AGENT',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('legal_address', sa.Text(), nullable=False),
    sa.Column('actual_address', sa.Text(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('ogrnip', sa.String(length=15), nullable=False),
    sa.Column('account_number', sa.String(length=34), nullable=False),
    sa.Column('correspondent_account', sa.String(length=34), nullable=False),
    sa.Column('bic', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('AUDIT_LOG',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('DOCUMENT_TYPE',
    sa.Column('type_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('type_code')
    )
    op.create_table('STAGE',
    sa.Column('stage_code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('stage_code')
    )
    op.create_table('STATUS',
    sa.Column('status_code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('status_code')
    )
    op.create_table('CLIENT',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['AGENT.agent_id'], ),
    sa.ForeignKeyConstraint(['current_stage'], ['STAGE.stage_code'], ),
    sa.ForeignKeyConstraint(['status_code'], ['STATUS.status_code'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('DOCUMENT',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('type_code', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['CLIENT.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_code'], ['DOCUMENT_TYPE.type_code'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('PASSPORT',
    sa.Column('passport_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('birth_place', sa.Text(), nullable=False),
    sa.Column('series_number', sa.String(length=20), nullable=False),
    sa.Column('issued_by', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('registration_address', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['CLIENT.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('passport_id'),
    sqlite_autoincrement=True
    )
    op.create_table('PHONE',
    sa.Column('phone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['CLIENT.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phone_id')
    )
    op.create_table('REMINDER',
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_stage', sa.String(length=32), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['CLIENT.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_stage'], ['STAGE.stage_code'], ),
    sa.PrimaryKeyConstraint('reminder_id')
    )
    op.create_table('SNILS',
    sa.Column('snils_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=14), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['CLIENT.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snils_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SNILS')
    op.drop_table('REMINDER')
    op.drop_table('PHONE')
    op.drop_table('PASSPORT')
    op.drop_table('DOCUMENT')
    op.drop_table('CLIENT')
    op.drop_table('STATUS')
    op.drop_table('STAGE')
    op.drop_table('DOCUMENT_TYPE')
    op.drop_table('AUDIT_LOG')
    op.drop_table('AGENT')
    # ### end Alembic commands ###
