"""Health checking

Revision ID: 1f75b8905c2a
Revises: ff8fddb0819d
Create Date: 2025-10-09 00:10:17.530489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f75b8905c2a'
down_revision: Union[str, Sequence[str], None] = 'ff8fddb0819d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AGENT', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('AUDIT_LOG', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('CLIENT', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('CLIENT', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('CLIENT', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('CLIENT_agent_id_fkey'), 'CLIENT', type_='foreignkey')
    op.create_foreign_key(None, 'CLIENT', 'AGENT', ['agent_id'], ['agent_id'], ondelete='RESTRICT')
    op.alter_column('DOCUMENT', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('PASSPORT', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('PHONE', 'number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('PHONE', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('REMINDER', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('SNILS', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SNILS', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('REMINDER', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('PHONE', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('PHONE', 'number',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('PASSPORT', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('DOCUMENT', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'CLIENT', type_='foreignkey')
    op.create_foreign_key(op.f('CLIENT_agent_id_fkey'), 'CLIENT', 'AGENT', ['agent_id'], ['agent_id'])
    op.alter_column('CLIENT', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('CLIENT', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('CLIENT', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('AUDIT_LOG', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('AGENT', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###

