"""Modules table added

Revision ID: 21f255e435af
Revises: 1f75b8905c2a
Create Date: 2025-11-18 12:01:46.389142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f255e435af'
down_revision: Union[str, Sequence[str], None] = '1f75b8905c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MODULES',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('patient', sa.String(length=64), nullable=False),
    sa.Column('modules', sa.String(length=64), nullable=False),
    sa.Column('catalogue_index', sa.String(length=64), nullable=False),
    sa.Column('supplier', sa.String(length=64), nullable=False),
    sa.Column('ordered', sa.String(length=64), nullable=False),
    sa.Column('order_date_acc_num', sa.String(length=64), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('received_stored', sa.String(length=64), nullable=False),
    sa.Column('pending', sa.String(length=64), nullable=False),
    sa.Column('recd', sa.String(length=64), nullable=False),
    sa.Column('properties', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['CLIENT.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.alter_column('AGENT', 'correspondent_account',
               existing_type=sa.VARCHAR(length=34),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AGENT', 'correspondent_account',
               existing_type=sa.VARCHAR(length=34),
               nullable=False)
    op.drop_table('MODULES')
    # ### end Alembic commands ###
