"""Recd mismatches

Revision ID: 3cba6fb12ba4
Revises: 6c7ccefa268e
Create Date: 2025-11-21 18:25:32.476700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cba6fb12ba4'
down_revision: Union[str, Sequence[str], None] = '6c7ccefa268e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MODULES', sa.Column('recd', sa.String(length=64), nullable=False))
    op.drop_column('MODULES', 'received_stored')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MODULES', sa.Column('received_stored', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('MODULES', 'recd')
    # ### end Alembic commands ###

