"""Agent.name ammendment_2

Revision ID: 540c2b87d359
Revises: 7e636798aacb
Create Date: 2025-08-14 11:10:54.048964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540c2b87d359'
down_revision: Union[str, Sequence[str], None] = '7e636798aacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AGENT', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('AGENT', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('AGENT', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AGENT', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('AGENT', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('AGENT', 'last_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
