"""Typos and errors

Revision ID: 6c7ccefa268e
Revises: c01bc196e0e9
Create Date: 2025-11-21 18:12:10.303815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7ccefa268e'
down_revision: Union[str, Sequence[str], None] = 'c01bc196e0e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MODULES', sa.Column('module_name', sa.String(length=64), nullable=False))
    op.drop_column('MODULES', 'module')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MODULES', sa.Column('module', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('MODULES', 'module_name')
    # ### end Alembic commands ###
