"""Agent.name ammendment

Revision ID: 7e636798aacb
Revises: 0bb747eb022a
Create Date: 2025-08-12 23:12:01.575952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e636798aacb'
down_revision: Union[str, Sequence[str], None] = '0bb747eb022a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('AGENT', sa.Column('last_name', sa.String(length=128), nullable=False))
    #op.add_column('AGENT', sa.Column('first_name', sa.String(length=128), nullable=False))
    #op.add_column('AGENT', sa.Column('middle_name', sa.String(length=128), nullable=False))
    #op.drop_column('AGENT', 'name')
    # ### end Alembic commands ###
    op.alter_column(
        "AGENT", 
        "name",
        new_column_name = "last_name",
        existing_type = sa.Text(),
        existing_nullable = False
    )

    op.add_column("AGENT", sa.Column("first_name", sa.String(length = 128), nullable = True))
    op.add_column("AGENT", sa.Column("middle_name", sa.String(length = 128), nullable = True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('AGENT', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    # op.drop_column('AGENT', 'middle_name')
    # op.drop_column('AGENT', 'first_name')
    # op.drop_column('AGENT', 'last_name')
    # ### end Alembic commands ###
