"""Refactor module ownership

Revision ID: c01bc196e0e9
Revises: f6df39151646
Create Date: 2025-11-18 19:07:50.759850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01bc196e0e9'
down_revision: Union[str, Sequence[str], None] = 'f6df39151646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('MODULES', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('MODULES', 'patient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MODULES', sa.Column('patient', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.alter_column('MODULES', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###

