"""Modules table ammendments

Revision ID: f6df39151646
Revises: 21f255e435af
Create Date: 2025-11-18 18:46:18.726011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6df39151646'
down_revision: Union[str, Sequence[str], None] = '21f255e435af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MODULES', sa.Column('module', sa.String(length=64), nullable=False))
    op.add_column('MODULES', sa.Column('quantity', sa.Integer(), nullable=False))
    op.alter_column('MODULES', 'patient',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('MODULES', 'modules')
    op.drop_column('MODULES', 'recd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MODULES', sa.Column('recd', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('MODULES', sa.Column('modules', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.alter_column('MODULES', 'patient',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('MODULES', 'quantity')
    op.drop_column('MODULES', 'module')
    # ### end Alembic commands ###

