[theme]
primaryColor = "#1fb1aaff"           # Морская волна
backgroundColor = "#f2f2f2ff"        # Белый фон
secondaryBackgroundColor = "#67cbc6ff" # Очень светло-зеленый (для фона инпутов)
textColor = "#2D3748"              # Темно-серый
font = "sans serif"

base = "light"

[theme.accent]
background = "#45bea6ff"
text = "#2E8B57"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "viewer"
showErrorDetails = false

[browser]
gatherUsageStats = false